### ISSUE TITLE
Results are not appropriate for web platform

### ISSUE THREAD

**Issue by malivinayak** [OutdatedGuy/Whats-That-Anime#12]
**Description:**
The results for respective images which are downloaded from google are not proper. Actual anime is not matching with **Other Results** either

**To Reproduce one example**
1. Download this Death Note light Yagami Image [Click Here](https://www.thestreambible.com/wp-content/uploads/2022/01/Death-F-1024x564.jpg)
2. Upload this image to search the result
3. Result  
![result](https://user-images.githubusercontent.com/66154908/175538082-e479bc0e-58f4-4a46-904f-b114ff547140.jpg)

**Expected behavior**
Top result must be Death Note

**Screenshots**
Searched Images and there respective results
![Search Results](https://user-images.githubusercontent.com/66154908/175538327-37130cc8-3151-4388-ab7a-730524b86688.jpg)

**Desktop (please complete the following information):**
 - Browser - chrome Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by OutdatedGuy** [comment]
Yo @malivinayak, this is not really a `web` platform related issue and neither a bug.

The `API` used in the project is **_optimized_** to search only **Scenes** that are in the Anime. (i.e. screenshots)
It doesn't work for any anime related images but only for **_Actual Scenes_** from an Anime.

Closing this issue. 

Please try using [image1](https://fantasytopics.com/wp-content/uploads/2022/05/Death-Note-Characters-Heights-Age-and-Birthday-Analysis.png) or [image2](https://www.anime-planet.com/images/anime/screenshots/death-note-1048-1.jpg)

If you are still unsatisfied with the result, leave a comment and I'll reopen this issue.

Thanks for your contribution.

**Comment by malivinayak** [comment]
@OutdatedGuy  Thank You for clarification. It properly worked for scenes screenshot.
