### ISSUE TITLE
In desperate need of a new feature in Whats That Anime

### ISSUE THREAD

**Issue by RisingDemon** [OutdatedGuy/Whats-That-Anime#13]
I am a daily user of Whats that Anime, website as well as app. I have searched thousands of anime through it, it has simply made my life comforting. But I would like to see a new feature in it, **A Drag And Drop** option, it will be helpful to many user as well as myself.

**Comment by OutdatedGuy** [comment]
Yo @RisingDemon, I'm glad you liked my project.

A `Drag and Drop` option is a wonderful idea. The **Feature Request** is marked as valid.

It'll be worked on soon. Thanks for your contributions.

**Comment by RisingDemon** [comment]
Thank you very much, I'll definitely be trying this now.
